# Generated by Django 4.1.5 on 2024-03-12 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_amenities_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='room_count',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basemodel')),
                ('image', models.ImageField(upload_to='hotels')),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='home.hotel')),
            ],
            bases=('home.basemodel',),
        ),
    ]
