# Generated by Django 4.1.5 on 2024-03-12 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_hotel_room_count_hotelimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_name', to='home.hotel'),
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basemodel')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booking_type', models.CharField(choices=[('Pre Paid', 'Pre Paid'), ('Post Paid', 'Post Paid')], max_length=20)),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_booking', to='home.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('home.basemodel',),
        ),
    ]
